### ISSUE TITLE
Scroll position is set to top in Gatsby

### ISSUE THREAD

**Issue by bitttttten** [xiel/use-location-state#104]
When I trigger using push and you have scrolled down a bit, the window gets set back to 0,0. I wasn't sure if this was a problem with the router integration, because Gatsby is using reach router. Although I am not sure if this is the default behaviour or not!

This is my code:

```js

import { useLocationState } from "use-location-state"

//

const [
	isViewingContactDetails,
	setIsViewingContactDetails,
] = useLocationState(`${data.id}-contactdetails`, false)
const onViewContactDetails = () => setIsViewingContactDetails(true, { method: "push" })
```

**Comment by xiel** [comment]
Thanks for opening an issue.

Can you share the code where onViewContactDetails is called?
Normally it should not scroll up, maybe you need to prevent the click.

**Comment by bitttttten** [comment]
I set it to

```js
onClick={e => {
	e.preventDefault()
	onViewContactDetails()
}}
```

Although it still scrolls up. I also set it to run in a setTimeout, and also put it on the window to call it. All 3 times the browser still scrolled to the top.

I guess then it might be an integration issue with Gatsby and/or @reach/router?

**Comment by xiel** [comment]
@bitttttten Which component is the onClick prop on? any other props? 
I will try to reproduce with gatsby & reach router.

**Comment by bitttttten** [comment]
It's a very generic component.. it's here:

```js

function InquireNow({ id }) {
	const [
		isViewingContactDetails,
		setIsViewingContactDetails,
	] = useLocationState(`${id}-contactdetails`, false)

	const onViewContactDetails = () =>
		setIsViewingContactDetails(true, { method: "push" })
	const closeIsViewingContactDetails = () => window.history.back()

	return (
		<>
			<DefaultButton
				css={(theme: TTheme) => ({
					marginTop: theme.spacing.l,
					display: `block`,
					width: `100%`,
				})}
				onClick={onViewContactDetails}
			>
				Inquire now
			</DefaultButton>
			<Modal
				isOpen={isViewingContactDetails}
				onClose={closeIsViewingContactDetails}
			>
				<H2
					css={(theme: TTheme) => ({
						marginBottom: theme.spacing.m,
						[mq.large]: {
							marginBottom: theme.spacing.l,
						},
						[mq.xxlarge]: {
							marginBottom: theme.spacing.xxl,
						},
						textAlign: `center`,
					})}
				>
					Contact Us
				</H2>
				<ContactForm />
			</Modal>
		</>
	)
}
```

**Comment by bitttttten** [comment]
I am not sure if this helps, but I can run:

```js
history.replaceState({page: 3}, "title 3", "?page=3")
```

and

```js
history.pushState({page: 1}, "title 1", "?page=1")
```

In the console and the page does not snap to the top!

**Comment by xiel** [comment]
Yes, thanks! I think I know the reason for it (I trigger a popstate event to notify all routing libs about a state change), reach router seems to always scroll up on popstate. I think I will make that optional, but it might take me a few days.
Thanks for your patience and for reporting.

**Comment by bitttttten** [comment]
Is it [this](https://github.com/xiel/use-location-state/blob/5824778c208969a0d25a8fa8e669563abd6f66ad/src/packages/use-location-state/src/useLocationState/useLocationStateInterface.ts#L41-L43) part?

**Comment by xiel** [comment]
@bitttttten Yes, I meant that part. Actually I found out that it is not react-router itself, but Gatsby doing that unwanted scrolling on each location change it notices.

Can you try adding this to your **gatsby-browser.js** file in gatsby root folder? 
```
// keeps same scroll pos when history state is pushed/replaced (same location === same position)
// see: https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll
exports.shouldUpdateScroll = ({ routerProps, getSavedScrollPosition }) => {
  const currentPosition = getSavedScrollPosition(routerProps.location)
  return currentPosition || true
}
```

Other modifications were not needed in my test to make it not scroll up on updates of location state.

**Comment by bitttttten** [comment]
Oh that works! Thanks so much!

Shall I close this issue up?

**Comment by xiel** [comment]
Great, thanks for bringing up this topic! 

I added a section to the readme about it:
https://github.com/xiel/use-location-state#gatsby--reachrouter
