### ISSUE TITLE
useLocationState usage ( to store and retrive)

### ISSUE THREAD

**Issue by totalcloud-tc** [xiel/use-location-state#116]
@xiel

**Comment by xiel** [comment]
It's works like a state hook, you have to call it from a react function body and you will receive the value and a setter function. 

`const [commentText, setCommentText] = useLocationState('someKey', 'default text')`
https://github.com/xiel/use-location-state#uselocationstate

There is also a codesandbox linked
http://bit.ly/useQueryStateDemo
