### ISSUE TITLE
Update to work with react-router-dom@5.2.0?

### ISSUE THREAD

**Issue by jrnail23** [xiel/use-location-state#212]
Hi, I just tried using `react-router-use-location-state`, and when I use `useQueryState`, I get an error saying `missing context export from react-router`.
It looks like this depends on a the router context being exported from react-router, but I guess it's no longer exported as expected.
Is there any chance you'll be updating this package to work with newer versions of react-router?

**Comment by xiel** [comment]
Thanks for raising this issue, yes, I will look into it this week.

**Comment by xiel** [comment]
Hi @jrnail23 ,

I was unable to reproduce the error with v5.2.0. This [demo](https://codesandbox.io/s/github/xiel/use-location-state/tree/master/src/examples/react-router-use-location-state?fontsize=14&module=%2Fsrc%2Fpages%2FQueryStateDemo.tsx) also uses 5.2.0 and works fine (range ^5.1.2, installed 5.2.0).

Please make sure you have react-router-dom defined & installed as a dependency (check node_modules folder), it is only defined as a peerDependency for this package.

I was able to produce error with react-router v6 (the next future major release) tho, but it is still in **beta**, so my compatibility update to it will happen after it is stable.

Hope that helps!
– Felix

**Comment by jrnail23** [comment]
actually, the package only specified `react-router` as a peer dep, not `react-router-dom`... not sure if that makes a difference or not, since I have `react-router-dom@5.2` installed, which has `react-router` as a dependency.

**Comment by jrnail23** [comment]
@xiel , so everything seems to work fine for me in the browser, but I'm getting the above error when running tests in Jest.  Any thoughts? Also, I'm using TypeScript 4.3.5, if that helps any.

**Comment by jrnail23** [comment]
@xiel, it turns out that this was due to a conflicting react-router version on my side.  Thanks for looking into it.
