### ISSUE TITLE
`useQueryState` value does not update when `defaultValue` changes

### ISSUE THREAD

**Issue by IPWright83** [xiel/use-location-state#345]
According to the docs when you call `useQueryState` you can pass through a default value. 

If you change this default value however, the `value` returned by `useQueryState` retains the old default value set. It seems like some internal state is being set to the default, which does not get updated when we modify the `defaultValue` being passed in. This means the return value of `useQueryState` is neither grabbing the state from the URL, nor returning the default value in this situation.

Pseudocode example:
```
const [defaultValue, setDefaultValue] = useState("foo");
const [value] = useQueryState("my-value", defaultValue);

useEffect(() => {
   setDefaultValue("bar");
});

console.log(value); // foo, foo (should be foo, bar)
```

**Comment by IPWright83** [comment]
This line https://github.com/xiel/use-location-state/blob/master/src/packages/use-location-state/src/useQueryState/useQueryReducer.ts#L66 explains why. I'd suggest currently the name `defaultValue` should be `initialValue` but I'd be interested to know if we could extend to allow changing the `defaultValue` (needed for our use case).

**Comment by xiel** [comment]
Hey @IPWright83 

yes you are right, the naming defaultValue in the readme might be a bit misleading. It is indeed meant as initial (also called like that in code, my bad). It was decided back than, to align the behaviour with reacts native useState which also takes an initialValue or init func.

Can you elaborate more on the use case?
Would a workaround like this work for you?

```
const [defaultValue, setDefaultValue] = useState("foo");
const [urlValue] = useQueryState("my-value", "");
const activeValue = urlValue || defaultValue;

useEffect(() => {
   setDefaultValue("bar");
}, []);

console.log(activeValue); // should always be ok :)
```

Cheers!

**Comment by IPWright83** [comment]
I see, explaining that you're trying to replicate the `useState` interface makes sense. I could try using a workaround like you've suggested, although it's not as ideal (as we do this in a few places, and the default value is calculated sometimes). 

I've also got a fork with a fix in (I'll be raising a PR soon), I wonder if the functionality could be added and sit behind an option flag?

**Comment by xiel** [comment]
@IPWright83 I think the main problem is the init function.

People usually pass them as inline arrow functions, which is ok, because they are only called once initially. Checking their identity does not work due to this, and calling and checking the return might be expensive.

So as it is easy to work around, I would think I'd like to keep the current behaviour, but I will update the readme.
You could make this reusable throughout your codebase using a custom hook I think.

**Comment by IPWright83** [comment]
@xiel thanks, I can see that could be a problem. I'll put a PR together (which doesn't take into account that someone may not be using a `useCallback`), but appreciate if you don't want to merge.

Will use the workaround for now at least. I realised it also involves changing a bunch of types, so instead of `useQueryState<MyType>` it now needs to be `useQueryState<MyType | undefined>`

**Comment by IPWright83** [comment]
@xiel actually thinking about it, won't the workaround you suggested result in a different behaviour? Imagine the situation:

So this won't work as default's don't currently update
```
const [defaultValue, setDefaultValue = useState("foo");
const [value, setValue] = useQueryState("value", defaultValue); // foo, ?value=undefined

setValue("bar"); // bar, ?value=bar
setDefaultValue("bar"); // bar, ?value=bar
setValue("foo"); // foo, ?value=undefined -- this is an error as the queryString should contain `bar`
```

Adding the workaround, I think the actual value will get out of sync?
```
const [defaultValue, setDefaultValue] = useState("foo");
const [qsValue, setvalue] = useQueryState("value", undefined);
const value = qsValue ?? defaultValue; // foo, ?value=undefined

setValue("bar"); // bar, ?value=bar
setDefaultValue("bar"); // bar, ?value=bar 
setValue("foo"); // bar, ?value=undefined -- this is an error as `value` should be `foo`
```

I'll try and build a quick example

**Comment by xiel** [comment]
`undefined` is not a valid initial / default value. (it required to be `string | number | boolean | Date | string[]`)
It is needed, so the query string can be parsed and transformed correctly. eg. a number will automatically always be returned as a number (10), not "10". For this, we need to inspect the initial value type.

depending on your values, I would suggest you pass -1, 0, or ""

`const value = qsValue === initialValue ? defaultValue : qsValue;`

**Comment by xiel** [comment]
I don't really understand the problem here? When there is a query value, then this value will be active and the default value will not be taken.  Sounds reasonable to me. But I guess it depends on the use case.

If you want to remove the qsValue when you change the default value, you can do it surely.

```tsx
<button
  onClick={() => {
    setDefaultValue("foo");
    setValue(null);
  }}
>
  Set default to "foo"
</button>
```

https://codesandbox.io/s/use-location-state-demo-49n1kw?file=/src/App.tsx:489-557

**Comment by IPWright83** [comment]
Yeah, @xiel that's the problem I'm trying to highlight - that unfortunately the default doesn't get removed when you try and change it. 

Unfortunately this is a very contrived example and resetting the value with a call to `setValue` would be incredibly difficult for me to achieve without breaking encapsulation. If need be I can always publish a fork and we could use that for now - though I'd still be interested to know if you'd consider the functionality with an additional option being passed through, as it seems useful?

**Comment by xiel** [comment]
Sorry, but I can't follow. Can't see a problem. 

The code example I posted works and don't see any breaking of encapsulation.

Even the most weird coupling you want, you can just implement that in a custom hook.
