### ISSUE TITLE
Support Next.js (SSR)

### ISSUE THREAD

**Issue by AndrewMeleka** [xiel/use-location-state#414]
I see this warning when the page is SSR type, any solution
**useLayoutEffect does nothing on the server**

Thanks

**Comment by xiel** [comment]
@AndrewMeleka Which SSR Framework are you using? Usually this warning should not hinder functionality (client-side).

We might need to add support for next (server-side) tho, because they use a different router.

**Comment by AndrewMeleka** [comment]
Framework: Next.js
- ye when working in client side is fine but the problem happens on SSG/SSR pages

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xiel** [comment]
@AndrewMeleka Thanks for the clarification. I'll have a look at it, but it might take a few days.

**Comment by xiel** [comment]
Support for Next.js was released: [📦 v.3.1.1](https://github.com/xiel/use-location-state/releases/tag/v3.1.1)

Hope it works for you @AndrewMeleka. Thanks for opening the issue!
